In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/analytics_sales.csv")

In [3]:
print(df.shape)

df.head()

(2925, 35)

,order_item_id,order_id,product_id,quantity,unit_price,subtotal,customer_id,order_date,order_status,product_name,category_id,price,stock_quantity,category_name,name,email,gender,age,city,membership,signup_date,payment_id,payment_method,payment_status,payment_amount,shipping_id,shipping_city,shipping_status,delivery_days,year,month,month_name,day,day_name,hour
0,ITEM000001,ORD00001,PROD0009,1,151.59,151.59,CUST0008,2025-07-19 10:58:15,Completed,Hoodie,CAT002,151.59,84,Fashion,Maria Lynch,amandasanchez@example.com,Female,40,Shah Alam,Silver,2025-04-12,PAY00001,Online Banking,Paid,269.25,SHP00001,Shah Alam,Delivered,3,2025,7,July,19,Saturday,10
1,ITEM000002,ORD00001,PROD0013,1,117.66,117.66,CUST0008,2025-07-19 10:58:15,Completed,Sunscreen,CAT003,117.66,238,Beauty,Maria Lynch,amandasanchez@example.com,Female,40,Shah Alam,Silver,2025-04-12,PAY00001,Online Banking,Paid,269.25,SHP00001,Shah Alam,Delivered,3,2025,7,July,19,Saturday,10
2,ITEM000003,ORD00002,PROD0013,1,117.66,117.66,CUST0051,2026-01-02 05:55:14,Completed,Sunscreen,CAT003,117.66,238,Beauty,Michael Dixon,donnacampbell@example.net,Female,59,Shah Alam,Bronze,2025-10-14,PAY00002,E-Wallet,Paid,117.66,SHP00002,Shah Alam,Delivered,3,2026,1,January,2,Friday,5
3,ITEM000004,ORD00003,PROD0008,2,412.18,824.36,CUST0101,2026-01-23 17:15:31,Completed,Sneakers,CAT002,412.18,121,Fashion,Juan Reyes,michellehill@example.com,Male,28,Johor Bahru,Gold,2025-03-14,PAY00003,E-Wallet,Paid,1346.74,SHP00003,Johor Bahru,Delivered,3,2026,1,January,23,Friday,17
4,ITEM000005,ORD00003,PROD0019,2,228.39,456.78,CUST0101,2026-01-23 17:15:31,Completed,Bedsheet,CAT004,228.39,94,Home,Juan Reyes,michellehill@example.com,Male,28,Johor Bahru,Gold,2025-03-14,PAY00003,E-Wallet,Paid,1346.74,SHP00003,Johor Bahru,Delivered,3,2026,1,January,23,Friday,17

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Data columns (total 35 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    2925 non-null   object
 1   order_id         2925 non-null   object
 2   product_id       2925 non-null   object
 3   quantity         2925 non-null   int64
 4   unit_price       2925 non-null   float64
 5   subtotal         2925 non-null   float64
 6   customer_id      2925 non-null   object
 7   order_date       2925 non-null   object
 8   order_status     2925 non-null   object
 9   product_name     2925 non-null   object
 10  category_id      2925 non-null   object
 11  price            2925 non-null   float64
 12  stock_quantity   2925 non-null   int64
 13  category_name    2925 non-null   object
 14  name             2925 non-null   object
 15  email            2925 non-null   object
 16  gender           2925 non-null   object
 17  age              2925 non-null   int64
 18  city             2925 non-null   object
 19  membership       2925 non-null   object
 20  signup_date      2925 non-null   object
 21  payment_id       2925 non-null   object
 22  payment_method   2925 non-null   object
 23  payment_status   2925 non-null   object
 24  payment_amount   2925 non-null   float64
 25  shipping_id      2925 non-null   object
 26  shipping_city    2925 non-null   object
 27  shipping_status  2925 non-null   object
 28  delivery_days    2925 non-null   int64
 29  year             2925 non-null   int64
 30  month            2925 non-null   int64
 31  month_name       2925 non-null   object
 32  day              2925 non-null   int64
 33  day_name         2925 non-null   object
 34  hour             2925 non-null   int64
dtypes: float64(4), int64(8), object(23)
memory usage: 799.9+ KB

In [5]:
df.describe()

,quantity,unit_price,subtotal,price,stock_quantity,age,payment_amount,delivery_days,year,month,day,hour
count,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000
mean,1.431453,231.289385,328.098595,231.289385,178.275897,38.137436,705.528564,3.531282,2025.514872,6.662564,15.901880,14.872821
std,0.782745,232.832349,401.336003,232.832349,62.392689,12.334607,679.169653,1.305883,0.499864,3.413277,8.911382,5.430278
min,1.000000,32.290000,32.290000,32.290000,67.000000,18.000000,32.290000,1.000000,2025.000000,1.000000,1.000000,0.000000
25%,1.000000,67.940000,87.010000,67.940000,121.000000,28.000000,226.840000,3.000000,2025.000000,4.000000,8.000000,11.000000
50%,1.000000,120.440000,169.580000,120.440000,186.000000,37.000000,513.180000,3.000000,2026.000000,7.000000,16.000000,16.000000
75%,2.000000,283.710000,412.180000,283.710000,237.000000,47.000000,955.560000,4.000000,2026.000000,10.000000,24.000000,20.000000
max,5.000000,852.390000,3409.560000,852.390000,265.000000,65.000000,4768.060000,7.000000,2026.000000,12.000000,31.000000,23.000000

In [6]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [7]:
print("Customers :", df["customer_id"].nunique())
print("Orders    :", df["order_id"].nunique())
print("Products  :", df["product_id"].nunique())

Customers : 483
Orders    : 1724
Products  : 25

In [8]:
customer_df = (
    df.groupby("customer_id")
      .agg(
          total_revenue=("subtotal", "sum"),
          total_orders=("order_id", "nunique"),
          average_order_value=("subtotal", "mean"),
          total_quantity=("quantity", "sum"),
          age=("age", "first"),
          gender=("gender", "first"),
          city=("city", "first"),
          membership=("membership", "first"),
          favorite_payment=("payment_method", lambda x: x.mode()[0]),
          favorite_category=("category_name", lambda x: x.mode()[0]),
          signup_date=("signup_date", "first"),
          first_purchase=("order_date", "min"),
          last_purchase=("order_date", "max")
      )
      .reset_index()
)

In [9]:
customer_df.head()

,customer_id,total_revenue,total_orders,average_order_value,total_quantity,age,gender,city,membership,favorite_payment,favorite_category,signup_date,first_purchase,last_purchase
0,CUST0001,4122.92,3,412.292000,16,19,Female,Kuala Lumpur,Bronze,Online Banking,Electronics,2026-04-22,2025-07-21 10:18:18,2026-04-08 12:50:57
1,CUST0002,1972.85,5,328.808333,10,43,Female,Shah Alam,Bronze,Credit Card,Home,2024-12-01,2025-09-01 06:45:23,2026-06-11 20:14:59
2,CUST0003,2398.45,4,342.635714,9,19,Male,Kuala Lumpur,Bronze,Credit Card,Electronics,2025-05-13,2025-12-29 22:26:55,2026-07-01 19:11:33
3,CUST0004,754.83,4,125.805000,7,27,Male,Johor Bahru,Bronze,Credit Card,Beauty,2025-09-23,2025-08-24 07:24:47,2026-07-10 20:26:33
4,CUST0005,815.99,4,135.998333,6,40,Male,Shah Alam,Bronze,Online Banking,Beauty,2025-10-04,2025-08-17 20:35:55,2026-06-13 07:59:57

In [10]:
from datetime import datetime

today = df["order_date"].max()

customer_df["customer_tenure_days"] = (
    today - customer_df["signup_date"]
).dt.days

customer_df["days_since_last_purchase"] = (
    today - customer_df["last_purchase"]
).dt.days

customer_df["purchase_frequency"] = (
    customer_df["total_orders"] /
    (customer_df["customer_tenure_days"] / 30)
).round(2)

customer_df["average_items_per_order"] = (
    customer_df["total_quantity"] /
    customer_df["total_orders"]
).round(2)

In [11]:
customer_df[
    [
        "customer_id",
        "total_revenue",
        "total_orders",
        "purchase_frequency",
        "customer_tenure_days",
        "days_since_last_purchase",
        "average_items_per_order",
    ]
].head()

,customer_id,total_revenue,total_orders,purchase_frequency,customer_tenure_days,days_since_last_purchase,average_items_per_order
0,CUST0001,4122.92,3,1.14,79,93,5.33
1,CUST0002,1972.85,5,0.26,586,29,2.00
2,CUST0003,2398.45,4,0.28,423,9,2.25
3,CUST0004,754.83,4,0.41,290,0,1.75
4,CUST0005,815.99,4,0.43,279,27,1.50

In [12]:
customer_df["total_revenue"].describe()

count     483.000000
mean     1986.932484
std      1500.277858
min        32.290000
25%       863.620000
50%      1622.560000
75%      2781.480000
max      8026.030000
Name: total_revenue, dtype: float64

In [13]:
threshold = customer_df["total_revenue"].quantile(0.75)

customer_df["high_value_customer"] = (
    customer_df["total_revenue"] >= threshold
).astype(int)

In [14]:
customer_df["high_value_customer"].value_counts()

high_value_customer
0    362
1    121
Name: count, dtype: int64

In [15]:
customer_df.head()

,customer_id,total_revenue,total_orders,average_order_value,total_quantity,age,gender,city,membership,favorite_payment,favorite_category,signup_date,first_purchase,last_purchase,customer_tenure_days,days_since_last_purchase,purchase_frequency,average_items_per_order,high_value_customer
0,CUST0001,4122.92,3,412.292000,16,19,Female,Kuala Lumpur,Bronze,Online Banking,Electronics,2026-04-22,2025-07-21 10:18:18,2026-04-08 12:50:57,79,93,1.14,5.33,1
1,CUST0002,1972.85,5,328.808333,10,43,Female,Shah Alam,Bronze,Credit Card,Home,2024-12-01,2025-09-01 06:45:23,2026-06-11 20:14:59,586,29,0.26,2.00,0
2,CUST0003,2398.45,4,342.635714,9,19,Male,Kuala Lumpur,Bronze,Credit Card,Electronics,2025-05-13,2025-12-29 22:26:55,2026-07-01 19:11:33,423,9,0.28,2.25,0
3,CUST0004,754.83,4,125.805000,7,27,Male,Johor Bahru,Bronze,Credit Card,Beauty,2025-09-23,2025-08-24 07:24:47,2026-07-10 20:26:33,290,0,0.41,1.75,0
4,CUST0005,815.99,4,135.998333,6,40,Male,Shah Alam,Bronze,Online Banking,Beauty,2025-10-04,2025-08-17 20:35:55,2026-06-13 07:59:57,279,27,0.43,1.50,0

In [16]:
customer_df.to_csv(
    "../data/customer_features.csv",
    index=False
)

print("Customer feature dataset saved successfully!")

Customer feature dataset saved successfully!