In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../data/customer_future_features.csv")

df.head()

,customer_id,historical_revenue,total_orders,total_quantity,average_item_value,age,gender,city,membership,favorite_payment,...,last_purchase,customer_tenure_days,days_since_last_purchase,purchase_frequency,average_items_per_order,historical_average_order_value,future_revenue,future_orders,future_value_score,future_high_value_customer
0,CUST0001,4122.92,3,16,412.2920,19,Female,Kuala Lumpur,Bronze,Online Banking,...,2026-04-08 12:50:57,1,2,90.000,5.33,1374.31,0.00,0,42393.672978,1
1,CUST0002,1178.80,2,3,589.4000,43,Female,Shah Alam,Bronze,Credit Card,...,2025-11-30 18:24:28,495,130,0.121,1.50,589.40,794.05,3,-696.964437,0
2,CUST0003,87.01,1,1,87.0100,19,Male,Kuala Lumpur,Bronze,E-Wallet,...,2025-12-29 22:26:55,332,101,0.090,1.00,87.01,2311.44,3,-354.388581,0
3,CUST0004,72.08,1,1,72.0800,27,Male,Johor Bahru,Bronze,Credit Card,...,2025-08-24 07:24:47,199,229,0.151,1.00,72.08,682.75,3,-1289.624349,0
4,CUST0005,335.87,3,4,83.9675,40,Male,Shah Alam,Bronze,Online Banking,...,2026-03-27 19:29:43,188,13,0.479,1.33,111.96,480.12,1,-93.757816,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 459 entries, 0 to 458
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   customer_id                     459 non-null    object
 1   historical_revenue              459 non-null    float64
 2   total_orders                    459 non-null    int64
 3   total_quantity                  459 non-null    int64
 4   average_item_value              459 non-null    float64
 5   age                             459 non-null    int64
 6   gender                          459 non-null    object
 7   city                            459 non-null    object
 8   membership                      459 non-null    object
 9   favorite_payment                459 non-null    object
 10  favorite_category               459 non-null    object
 11  signup_date                     459 non-null    object
 12  first_purchase                  459 non-null    object
 13  last_purchase                   459 non-null    object
 14  customer_tenure_days            459 non-null    int64
 15  days_since_last_purchase        459 non-null    int64
 16  purchase_frequency              459 non-null    float64
 17  average_items_per_order         459 non-null    float64
 18  historical_average_order_value  459 non-null    float64
 19  future_revenue                  459 non-null    float64
 20  future_orders                   459 non-null    int64
 21  future_value_score              459 non-null    float64
 22  future_high_value_customer      459 non-null    int64
dtypes: float64(7), int64(7), object(9)
memory usage: 82.6+ KB

In [4]:
columns_to_remove = [
    "customer_id",
    "signup_date",
    "first_purchase",
    "last_purchase",
    "future_revenue",
    "future_orders",
    "future_value_score"   # <-- Add this
]

df = df.drop(columns=columns_to_remove)

In [5]:
X = df.drop(
    columns="future_high_value_customer"
)

y = df["future_high_value_customer"]

In [6]:
X.select_dtypes(include="object").columns

Index(['gender', 'city', 'membership', 'favorite_payment',
       'favorite_category'],
      dtype='object')

In [7]:
X = pd.get_dummies(
    X,
    drop_first=True,
    dtype=int
)

In [8]:
print(X.shape)

X.head()

(459, 27)

,historical_revenue,total_orders,total_quantity,average_item_value,age,customer_tenure_days,days_since_last_purchase,purchase_frequency,average_items_per_order,historical_average_order_value,...,membership_Platinum,membership_Silver,favorite_payment_Credit Card,favorite_payment_Debit Card,favorite_payment_E-Wallet,favorite_payment_Online Banking,favorite_category_Electronics,favorite_category_Fashion,favorite_category_Home,favorite_category_Sports
0,4122.92,3,16,412.2920,19,1,2,90.000,5.33,1374.31,...,0,0,0,0,0,1,1,0,0,0
1,1178.80,2,3,589.4000,43,495,130,0.121,1.50,589.40,...,0,0,1,0,0,0,1,0,0,0
2,87.01,1,1,87.0100,19,332,101,0.090,1.00,87.01,...,0,0,0,0,1,0,0,0,1,0
3,72.08,1,1,72.0800,27,199,229,0.151,1.00,72.08,...,0,0,1,0,0,0,0,1,0,0
4,335.87,3,4,83.9675,40,188,13,0.479,1.33,111.96,...,0,0,0,0,0,1,0,0,0,0

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [10]:
X_train.to_csv("../data/X_train.csv", index=False)
X_test.to_csv("../data/X_test.csv", index=False)
y_train.to_csv("../data/y_train.csv", index=False)
y_test.to_csv("../data/y_test.csv", index=False)

In [11]:
print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)
print("\nTarget distribution:")
print(y.value_counts())

Training set: (367, 27)
Testing set: (92, 27)

Target distribution:
future_high_value_customer
0    344
1    115
Name: count, dtype: int64

In [12]:
y.value_counts()

future_high_value_customer
0    344
1    115
Name: count, dtype: int64